[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = "Flask-Leticia"
version = "0.1"
dependencies = [
	"Flask",
	"flask_webpackext",
	"sqlalchemy",
]

[project.scripts]
leticia = "leticia.scripts:cli"
